# Release name
PRODUCT_RELEASE_NAME := YU5014

PRODUCT_DEVICE := YU5014
PRODUCT_NAME := lineage_YU5014
PRODUCT_BRAND := YU
PRODUCT_MODEL := YU5014
PRODUCT_MANUFACTURER := YU

PRODUCT_DEFAULT_LANGUAGE := en
PRODUCT_DEFAULT_REGION   := US
