# Release name
PRODUCT_RELEASE_NAME := YU5014

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRODUCT_NAME=YU5014 \
    BUILD_PRODUCT=YU5014 \
    TARGET_DEVICE=YU5014
    
    
PRODUCT_DEFAULT_LANGUAGE := en
PRODUCT_DEFAULT_REGION   := US
